name: Node CI

on:
  push:
    branches: '*'
  pull_request:
    branches : '*'
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: git submodule init, update
      run: |
        git submodule init
        git submodule update
    - name: npm install and test
      run: |
        npm install
        npm run test
      env:
        CI: true
